typeset -U path PATH

if [ -d /opt/homebrew/bin ]; then
  path=(/opt/homebrew/bin /opt/homebrew/sbin $path)
elif [ -d /usr/local/bin ]; then
  path=(/usr/local/bin /usr/local/sbin $path)
fi

export PATH
